discovery_page_block_html_1:
  default: ""
  type: string
  description: "HTML for block 1 on the discovery page"
discovery_page_block_html_2:
  default: ""
  type: string
  description: "HTML for block 2 on the discovery page"
discovery_page_block_html_3:
  default: ""
  type: string
  description: "HTML for block 3 on the discovery page"

discovery_categories_html:
  default: ""
  type: list
