discovery_page_block_html_1:
  default: ""
  type: string

discovery_page_block_html_2:
  default: ""
  type: string
discovery_page_block_html_3:
  default: ""
  type: string

discovery_page_top_block_html:
  default: ""
  type: string

discovery_javascript_code:
  default: ""
  type: string


discovery_categories_html:
  default: ""
  type: list
